import NavBar from "./components/NavBar"
import "./reset.css"
import "./styles/font.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
        {children}
        </body>
    </html>
  )
}
